FROM python:3.9

COPY . .

RUN pip install --disable-pip-version-check poetry
RUN poetry config virtualenvs.create false
RUN poetry install --no-dev

ENV PYTHONUNBUFFERED=1

CMD ["python", "monitor.py"]
